### ISSUE TITLE
Reuse of a rule in one class

### ISSUE THREAD

**Issue by M4rtinW** [codecentric/zucchini#18]
It is not possible to use a rule, defined in the parent class of a testclass, twice. 

Scenario:
I want to log into a system with two textfields. Both fields should be filled by reusing one rule. Therefore i need two ids, two texts and a rule who can handle two parameters.

When I run the test, the following behavior is observed.
Both texts are written to the last named textfield.

**Comment by visusnet** [comment]
This feature has been implemented in 2.1.0-SNAPSHOT and will be released immediately.
